In [141]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [142]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [143]:
df.shape

(569, 33)

In [144]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [145]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [146]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0],test_size=0.2)

In [147]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [148]:
x_train

array([[-0.74576475, -0.25417653, -0.74176222, ..., -0.85847644,
        -1.11155393, -0.37610486],
       [ 1.77378716,  0.31634687,  1.73521935, ...,  0.73561758,
         0.57884065, -1.07865301],
       [-0.38502979, -0.58603477, -0.38020641, ..., -0.47785104,
         0.32995844,  0.13958344],
       ...,
       [-0.69822603,  2.27567426, -0.68987977, ..., -0.65945859,
         0.01760292, -0.61066167],
       [ 0.88732994, -0.49966071,  0.85564972, ...,  1.10183445,
         0.44187192, -0.10956303],
       [-0.17530016, -1.49296241, -0.25131095, ..., -1.35361967,
        -1.01300326, -1.18751431]], shape=(455, 30))

In [149]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [150]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0])

In [151]:
#numpy to tensor
x_train_tensor = torch.tensor(x_train)
y_train_tensor = torch.tensor(y_train)
x_test_tensor = torch.tensor(x_test)
y_test_tensor = torch.tensor(y_test)

In [152]:
x_train_tensor.shape

torch.Size([455, 30])

In [153]:
x_train_tensor = x_train_tensor.to(torch.float32)
y_train_tensor = y_train_tensor.to(torch.float32)

In [154]:
#Define model
learning_rate = 0.1
epochs = 1000

In [155]:
import torch
import torch.nn as nn
class MySimpleNN(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

In [156]:
loss_function = nn.BCELoss()

In [157]:
model = MySimpleNN(x_train_tensor.shape[1])

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
# =========================
# Training Loop
# =========================

for epoch in range(epochs):

    # Forward Pass
    y_pred = model(x_train_tensor)

    # Compute Loss
    loss = loss_function(
        y_pred,
        y_train_tensor.view(-1, 1)
    )
    
    # Zero Gradients
    optimizer.zero_grad()

    # Backward Pass
    loss.backward()

    # Update Parameters
    optimizer.step()

    # Print Loss
    if epoch % 100 == 0:
        print(
            f"Epoch {epoch:4d} | Loss = {loss.item():.6f}"
        )

Epoch    0 | Loss = 0.731540
Epoch  100 | Loss = 0.081448
Epoch  200 | Loss = 0.061172
Epoch  300 | Loss = 0.054253
Epoch  400 | Loss = 0.050443
Epoch  500 | Loss = 0.047776
Epoch  600 | Loss = 0.045642
Epoch  700 | Loss = 0.043807
Epoch  800 | Loss = 0.042206
Epoch  900 | Loss = 0.040785

In [158]:
with torch.no_grad():

    y_pred = model.forward(x_train_tensor)

    predictions = (y_pred >= 0.5).float()

    accuracy = (
        predictions == y_train_tensor
    ).float().mean()

print(f"Accuracy: {accuracy.item()*100:.2f}%")

Accuracy: 53.36%

In [159]:
class MySimpleNN1:

    def __init__(self, X):

        # Initialize weights and bias
        self.weights = torch.randn(
            X.shape[1],
            1,
            dtype=torch.float32,
            requires_grad=True
        )

        self.bias = torch.zeros(
            1,
            dtype=torch.float32,
            requires_grad=True
        )

    def forward(self, X):

        y_pred = torch.sigmoid(
            torch.matmul(X, self.weights) + self.bias
        )

        return y_pred

    def loss_function(self, y_pred, y_true):

        epsilon = 1e-7

        y_pred = torch.clamp(
            y_pred,
            epsilon,
            1 - epsilon
        )

        loss = -(
            y_true * torch.log(y_pred)
            +
            (1 - y_true) * torch.log(1 - y_pred)
        ).mean()

        return loss

In [160]:
model = MySimpleNN1(x_train_tensor)


# =========================
# Training Loop
# =========================

for epoch in range(epochs):

    # Forward Pass
    y_pred = model.forward(x_train_tensor)

    # Compute Loss
    loss = model.loss_function(
        y_pred,
        y_train_tensor
    )

    # Backward Pass
    loss.backward()

    # Update Parameters
    with torch.no_grad():

        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # Zero Gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # Print Loss
    if epoch % 100 == 0:
        print(
            f"Epoch {epoch:4d} | Loss = {loss.item():.6f}"
        )

Epoch    0 | Loss = 1.998816
Epoch  100 | Loss = 0.777639
Epoch  200 | Loss = 0.719819
Epoch  300 | Loss = 0.703238
Epoch  400 | Loss = 0.695887
Epoch  500 | Loss = 0.691386
Epoch  600 | Loss = 0.688014
Epoch  700 | Loss = 0.685225
Epoch  800 | Loss = 0.682815
Epoch  900 | Loss = 0.680689

In [161]:
with torch.no_grad():

    y_pred = model.forward(x_train_tensor)

    predictions = (y_pred >= 0.5).float()

    accuracy = (
        predictions == y_train_tensor
    ).float().mean()

print(f"Accuracy: {accuracy.item()*100:.2f}%")

Accuracy: 61.14%